version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:8.10 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: 
          command: npm install
      - run:
          command: npm run build
      - store_artifacts:
          path: build

